pingidentity/pingidentity-devops-getting-started

- 12-docker-swarm/fullstack.yaml
Support for PingFederate clustering. 
@arnaudlacour 
@samirgandhi19 
@tsigle
> Update Swarm fullstack to include PingFederate clustering

- 11-docker-compose/03-full-stack/README.md
- README.md
- SUMMARY.md
- docs/PROD-LICENSE.md
- docs/README.md
- docs/getting-started/QUICKSTART.md
looking to help people get started with the available tools faster by suggesting articles based on what they are trying to accomplish.
> restructuring. added "learning paths".

- 11-docker-compose/03-full-stack/docker-compose.yaml
- 11-docker-compose/06-pingaccess-cluster/docker-compose.yaml
- 12-docker-swarm/fullstack.yaml
- 20-kubernetes/01-standalone/pingaccess/pingaccess.yaml
- 20-kubernetes/04-clustered-pingaccess/pingaccess-engine.yaml
to merge once PA 6.0.0 is 'edge'
> use PA 6.0.0-alpine-edge

- 10-docker-standalone/30-pingcentral/README.md
- 10-docker-standalone/30-pingcentral/env_vars
- 11-docker-compose/30-pingcentral/embedded-h2.yml
add examples for how to use PingCentral image with devops tooling
> update for pingcentral

- 11-docker-compose/07-pingdatagovernance/README.md
- 11-docker-compose/07-pingdatagovernance/docker-compose.yaml
- 20-kubernetes/01-standalone/pingdatagovernancepap/configmap.yaml
- 20-kubernetes/01-standalone/pingdatagovernancepap/kustomization.yaml
- 20-kubernetes/01-standalone/pingdatagovernancepap/pingdatagovernancepap.yaml
- 20-kubernetes/02-fullstack/env_vars.pingdatagovernancepap
- 20-kubernetes/02-fullstack/kustomization.yaml
adding k8 and docker compose configurations for datagov with pap
> Pdp pap integration

- 10-docker-standalone/README.md
- 11-docker-compose/03-full-stack/README.md
- 11-docker-compose/30-pingcentral/README.md
- 11-docker-compose/README.md
PingCentral docker is now supported. 
Added documentation for PingCentral.
> PingCentral documentation Updates

- SUMMARY.md
- docs/dockerImageSecurity.md
> Base image os

- 11-docker-compose/00-standalone/pingaccess/docker-compose.yaml
- 11-docker-compose/00-standalone/pingcentral/docker-compose.yaml
- 11-docker-compose/00-standalone/pingdirectory/docker-compose.yaml
- 11-docker-compose/00-standalone/pingfederate/docker-compose.yaml
- 11-docker-compose/01-simple-stack/docker-compose.yaml
- 11-docker-compose/02-replicated-pair/docker-compose.yaml
- 11-docker-compose/03-full-stack/docker-compose.yaml
- 11-docker-compose/04-simple-sync/docker-compose.yaml
- 11-docker-compose/05-pingfederate-cluster/docker-compose.yaml
- 11-docker-compose/06-pingaccess-cluster/docker-compose.yaml
- 11-docker-compose/07-pingdatagovernance/docker-compose.yaml
- 11-docker-compose/10-monitoring-stack/docker-compose.yaml
- 11-docker-compose/11-siem-stack/docker-compose.yaml
- 11-docker-compose/30-pingcentral/docker-compose.yml
- 11-docker-compose/30-pingcentral/embedded-h2.yaml
- docs/saveConfigs.md
- Update all compose files, adding volumes where needed
- Changed ~ to ${HOME} in env_file path
- Added ${PING_IDENTITY_DEVOPS_TAG} where edge was explicitly set
- excluded PA clustering due to server-profile version requirement
> GDO-301: Add volumes to docker compose files

- 20-kubernetes/02-fullstack/kustomization.yaml
- 20-kubernetes/02-fullstack/wait-for-directory.yaml
- 20-kubernetes/02-fullstack/wait-for-federate.yaml
> add "wait-for" for dependent pieces

- 20-kubernetes/12-pingdirectory-upgrade/1-inital.yaml
- 20-kubernetes/12-pingdirectory-upgrade/2-partition.yaml
- 20-kubernetes/12-pingdirectory-upgrade/3-staging.yaml
- 20-kubernetes/12-pingdirectory-upgrade/4-rollout.yaml
- 20-kubernetes/12-pingdirectory-upgrade/README.md
- SUMMARY.md
- docs/upgradePingDirectory.md
- added an example that should walk through a successful upgrade. 
- documented the example with some thoughts for best practices. 
probably should add a diagram.. but didn't
> initial docs with example for pd upgrade

- 99-helper-scripts/ping-bulkconfigtool/Dockerfile
I added a Dockerfile to encapsulate the building of this tool.  Feel free to close this PR and just publish an authoritative image on docker hub.  hint hint wink wink
> ping-bulkexport-tools dockerfile

- 99-helper-scripts/ping-bulkconfigtool/_pa-export-config.sh
- 99-helper-scripts/ping-bulkconfigtool/_pf-export-config.sh
closes #156  - uses variable in echo instead
> closes #156 - use variable in echo

- 11-docker-compose/13-pingdataconsole-pingone-sso/README.md
- 11-docker-compose/13-pingdataconsole-pingone-sso/docker-compose.yaml
- SUMMARY.md
- docs/deployPingDataConsoleSSO.md
Added a new docker-compose example and documentation for configuring
SSO with PingOne for pingdataconsole.
GDO-588
> Add docs and example for pingdataconsole SSO

- 11-docker-compose/00-standalone/pingdirectory/docker-compose.yaml
- 11-docker-compose/01-simple-stack/docker-compose.yaml
- 11-docker-compose/03-full-stack/docker-compose.yaml
- 11-docker-compose/04-simple-sync/docker-compose.yaml
- 11-docker-compose/12-sync-failover-pair/docker-compose.yaml
- 20-kubernetes/01-standalone/pingdataconsole/kustomization.yaml
- docs/deployment/deployPdgPap.md
- docs/deployment/deployReplication.md
- docs/get-started/getStartedWithGitRepo.md
Update PingData product logins to reflect service port
> Update PingData product login details

- docs/deployment/deployMonitoringStack.md
- docs/deployment/deployPaCluster.md
- docs/deployment/deployPdgPap.md
- docs/deployment/deployPfCluster.md
- docs/deployment/deployReplication.md
- docs/deployment/deploySimpleStack.md
I caught other incorrect passwords in other documents.
> replace incorrect password in individual docs

- 99-helper-scripts/ping-bulkconfigtool/ping-bulkexport-tools-project/in/pf-config.json
- 99-helper-scripts/ping-bulkconfigtool/ping-bulkexport-tools-project/src/main/java/com/pingidentity/apac/pf/bulkconfigtools/App.java
GDO-641 - Bulk export utility Expose-parameters: duplicate substitution
variable names (json path the same for multiple items)
> Fixes: GDO-641

- docs/overview.md
- mkdocs.yml
Move overview section into main section
> Gdo 650 docs nav

- docs/release-notes/relnotes-2012.md
Update release notes to included GDO-502
> Update 2012 release notes

- docs/reference/imageSupport.md
- docs/reference/releaseTags.md
- Remove active product versions 
- Active versions to be noted in release notes
> Active product versions in release notes

- docs/release-notes/relnotes-2102.md
- mkdocs.yml
Here is my stab at updating the release notes from the notes at https://jira.pingidentity.com/secure/ReleaseNote.jspa?projectId=17785&version=36524
Feel free to be nit-picky if anything is not up to your standards!
> Add release notes for 2102 release.

- docs/how-to/migratingRootToUnprivileged.md
> Add scheduled date for unprivileged changes

- docs/deployment/deployPingCentral.md
This PR contains changes to the documentation to account for the recent changes to the unprivileged user with the edge image. It also contains updated instructions.
> Update documentation for Deploying PingCentral

- 20-kubernetes/10-ingress/pingfederate-cluster-ingress.yaml
> Update for PF 10.2

- docs/release-notes/relnotes-2103.md
- mkdocs.yml
New release notes for March 2021 release.
> Update getting started docs with March 2021 release notes

- docs/how-to/buildPingDirectoryProfile.md
- docs/how-to/buildPingFederateProfile.md
- mkdocs.yml
> how to build a pd profile

- .github/workflows/docs.yml
- 11-docker-compose/03-full-stack/docker-compose.yaml
- 11-docker-compose/07-pingauthorize/README.md
- 11-docker-compose/07-pingauthorize/docker-compose.yaml
- docs/deployment/deployPazPap.md
- docs/docker-builds/README.md
- docs/get-started/getStartedWithGitRepo.md
- docs/how-to/existingLicense.md
- docs/reference/profileStructures.md
- docs/reference/usingCertificates.md
- mkdocs.yml
Note that in order for the redirect to work, the `mkdocs-redirects` plugin must be added to the server beforehand.
> Ds 44139 add pingauthorize

- docs/deployment/deployPingCentral.md
Please wait to merge until after July 1st 2021 when PingCentral 1.8 has been released.
> Update README for PingCentral 1.8 release

- docs/release-notes/relnotes-2107.md
- mkdocs.yml
Release notes for the 2107 release notes.
> 2107 release notes

- docs/mkdocs/overrides/stylesheets/extra.css
- Varialbize CSS to make future updates simplier
- Minor edits for dark mode consistency
- Clean up unused css classes
> Support dark theme

- docs/release-notes/relnotes-2106.md
- Update the HEAP awareness item to include all Ping built images
> 2106 Release notes update

- docs/reference/usingCertificates.md
Added PingData certificate rotation section related to GDO-914.
> Update usingCertificates.md to add PingData certificate rotation related to GDO-914

- 11-docker-compose/00-standalone/pingfederate/docker-compose.yaml
- 11-docker-compose/01-simple-stack/docker-compose.yaml
- 11-docker-compose/03-full-stack/docker-compose.yaml
- 11-docker-compose/05-pingfederate-cluster/docker-compose.yaml
- 11-docker-compose/11-siem-stack/docker-compose.yaml
Added default variables back for ease of use.
> Added PF_LDAP_USERNAME, PF_LDAP_PASSWORD in docker-compose.yaml examples

- docs/release-notes/currentRelease.md
- docs/release-notes/relnotes-2203.md
Added all Helm releases within the previous sprint
> updated helm chart section

- docs/get-started/getStarted.md
> BRASS-407: Write Pingctl Documentation for Exporting Configured Variables

- docs/get-started/pingctlUtil.md
- Update available commands reference to the correct file path and
name.
> BRASS-408: Fix Broken Links in Pingctl Available Commands Docs

- 30-helm/everything.yaml
- 30-helm/pingdirectory.yaml
- 30-helm/simple-sync.yaml
> Update server profile branch in Helm examples

- 30-helm/rbac.yaml
Added example showing various options for RBAC in the Helm chart.
BRASS-360
> Add example for RBAC with Helm

- 99-helper-scripts/ping-bulkconfigtool/ping-bulkexport-tools-project/src/main/java/com/pingidentity/apac/pf/bulkconfigtools/App.java
Fixing previous commit that required parent configuration for remove-config
> Fixing parent config for remove-config

- 30-helm/README.md
- docs/README.md
- docs/deployment/deployCompose.md
- docs/deployment/deployHelmLocalIngress.md
- docs/deployment/deployLocalK8sCluster.md
- docs/get-started/getStartedExample.md
- docs/get-started/prereqs.md
- docs/how-to/privateRepos.md
- docs/how-to/profilesLayered.md
- docs/reference/HelmBasics.md
- docs/release-notes/relnotes-2201.md
Following the site revamp of BRASS-490, several links to the Helm examples needed updating
Further editing
> Wordsmithing and correcting links to helm examples

- docs/get-started/getStartedExample.md
Fix an incorrect selector in the getting started example.
BRASS-490
> Fix getting started example commands

- docs/get-started/configVars.md
- docs/ping-devops/topics/devops-registration
- docs/reference/troubleshooting.md
- motd/motd.json
> Fix broken devops registration links

- docs/README.md
- docs/get-started/getStartedExample.md
- docs/reference/containerLogging.md
- mkdocs.yml
> logging reference page and links

- docs/README.md
- docs/docker-images/dockerImagesRef.md
- docs/docker-images/imageSupport.md
- mkdocs.yml
* additional emphasis on removal indicated in 3 locations on the portal
* move the retention policy from under subheading in left navigation for visibility
> BRASS-496 emphasizing retention policy for images

- docs/how-to/profilesPingDataExtensions.md
- docs/reference/profileStructures.md
- mkdocs.yml
> Document PingData extension installation

- 30-helm/rbac.yaml
> Add example using external service account to Helm RBAC example

- docs/get-started/getStartedExample.md
> Clarification on port-forwarding and services for new-to-k8s users

- 30-helm/rbac.yaml
> Use valid serviceAccountName in example

- docs/release-notes/relnotes-2108.md
> fix broken link

- docs/how-to/assignPFNodeId.md
- mkdocs.yml
> Add doc for PingFederate provisioner node id

- docs/how-to/profilesLayered.md
> Remove reference to deleted profile in Layered profile doc

- 30-helm/csi-secrets-volume.yaml
- docs/deployment/deployHelm.md
> Add CSI volume Helm example

- docs/deployment/deploymentPatterns.md
- Generalized server profile references (not the focus of the example)
- Readability & flow
- Grammar
> Closes BRASS-545

- docs/README.md
- docs/get-started/getStartedExample.md
- docs/home/portalUpdates.md
- docs/how-to/buildLocal.md
- docs/reference/config.md
- docs/reference/hooks.md
- docs/videos/videos.md
- closes BRASS-608
- update "portal updates" page, landing page to reference videos
- pages with video-related content updated with links
- videos tab updated
> BRASS-608 providing links and emphasis on videos across the portal

- 30-helm/pingfederate-cluster.yaml
- docs/deployment/deployLocalK8sCluster.md
- closes BRASS-611
- syncing up changes from getting started to this page
> BRASS-611 updating ref to getting started to include ingress

- docs/reference/hooks.md
- docs/videos/videos.md
linking in hook script video where appropriate
- Videos page
- Hook script detail page
> Closes BRASS-612

- docs/deployment/deployPACluster.md
- mkdocs.yml
Docs for default PA cluster pt2
> Docs for default PA cluster

- docs/videos/videos.md
> adding reference pipeline video

- 30-helm/everything-openshift.yaml
- docs/deployment/deployLocalOpenshift.md
- docs/videos/videos.md
- closes BRASS-696
- added video links for Openshift local
> Linking in Openshift video

- docs/reference/faqs.md
> adding FAQ on dockershim removal

- docs/docker-images/pingcentral/README.md
- docs/tools/pingctlUtil.md
> Remove depricated devops tool config refrences

- 30-helm/pingdirectory-backup/pingdirectory-periodic-backup.yaml
> Avoid running backup on non-master instances

- docs/docker-builds/README.md
- docs/reference/config.md
- closes BRASS-795
- better description of the page purpose and clarification of content
> fixing incomplete documentation page

- 20-kubernetes/splunk/values.yaml
- docs/how-to/splunkLogging.md
- docs/reference/k8sBasics.md
- docs/videos/videos.md
- closes BRASS-846
- incorporate video into Splunk and videos page
- minor site edits
> adding Splunk video

- 20-kubernetes/splunk/README.md
- docs/deployment/deployHelm.md
- docs/docker-images/dockerImagesRef.md
- docs/reference/faqs.md
- closes BRASS-854
- minor site edits
> update FAQ for notifications

- docs/deployment/deployFullK8s.md
- docs/videos/videos.md
> link in video of local k8s cluster

- 99-helper-scripts/ansible/ansible.cfg
- 99-helper-scripts/ansible/install_kubernetes.yaml
- 99-helper-scripts/ansible/install_list.yaml
- 99-helper-scripts/ansible/install_others.yaml
- 99-helper-scripts/ansible/inventory.ini
- docs/deployment/deployFullK8s.md
- closes BRASS-1058
- added instructions to use Ansible playbooks, keeping the manual process as reference
- added supporting files for using ansible
- provided workaround for ingress issue until helm charts can be updated
> Brass 1058 portal updates

- docs/deployment/deployK8s-AWS.md
- mkdocs.yml
Update the recommended method for communication between VPC's in a multi region example.
> multi region communication reccommendation

- docs/release-notes/currentRelease.md
Add the versions of pa and pf that are EOL to currentRelease.md.
> Add pa and pf vers EOL to currentRelease.md

- docs/release-notes/currentRelease.md
- docs/release-notes/relnotes-2307-1.md
- docs/release-notes/relnotes-2308-1.md
- mkdocs.yml
Release Notes for 2307.1 and 2308.1 file system permissions fix
> 2307.1 & 2308.1 relnotes

- docs/docker-images/dockerImagesRef.md
- docs/home/portalUpdates.md
- docs/reference/awsStorage.md
- docs/reference/faqs.md
- mkdocs.yml
- Closes BRASS-1206
- Guidance on EBS usage
> Add EFS-EBS statement

- docs/docker-images/imageSupport.md
- docs/home/supportPolicy.md
> Cross-linked Image and Devops support policy pages

- docs/reference/faqs.md
- docs/release-notes/relnotes-2109.md
- Closes BRASS-1318
- Correct link in old release note
> Add licensing FAQ entry

- docs/how-to/upgradePingCentral.md
- docs/videos/videos.md
> Adding video links for PingCentral upgrade demonstration

- 30-helm/multi-region/pingfederate/base.yaml
> Remove extraneous server profile refs now in baseline

- docs/how-to/prometheus.md
- mkdocs.yml
> Add prometheus page to how-to

- docs/how-to/devopsRegistration.md
> Add clarification for support

- docs/deployment/deployLocalOpenshift.md
> update Openshift Local instructions to current

- 30-helm/multi-region/pingdirectory-loadbalancer-per-pod/01-west.yaml
- 30-helm/multi-region/pingdirectory-loadbalancer-per-pod/02-east.yaml
- 30-helm/multi-region/pingdirectory/01-west.yaml
- 30-helm/multi-region/pingdirectory/02-east.yaml
- 30-helm/multi-region/pingfederate/01-layer-east.yaml
- 30-helm/multi-region/pingfederate/01-layer-west.yaml
- 30-helm/multi-region/pingfederate/02-layer-east.yaml
- docs/deployment/deployPFMultiRegion.md
> Align sample files with graphic

- DISCLAIMER.md
- LICENSE.md
- docs/build-docs.sh
- mkdocs.yml
- motd/README.md
> Update copyright year to 2025

- docs/docker-images/dockerImagesRef.md
- docs/reference/faqs.md
- closes PDI-2197
- provides clarity on the FedRAMP images
> Add Iron Bank clarification

- docs/docker-images/pingdirectory/README.md
- docs/docker-images/pingdirectoryproxy/README.md
> manual fix until release

- .github/workflows/slack-on-issue-create.yml
> Add slack notification with button workflow

- mkdocs.yml
> Add redirect for 2507 release notes
